### PR TITLE
Convert icon font to SVG

### PR DESCRIPTION
**Pull request by websupporter**
Solves https://github.com/pluginkollektiv/cachify/issues/40

Solution:
Instead of using CSS pseudo classes, this PR adds a `<svg>` in the `<a>` element.

I also added a gruntfile, since I did a lot with the CSS during my patch and this was more easy for me, letting the minified file be created automatically. I think future development can benefit from this.

### CODE REVIEW

**Comment by websupporter** [comment]
before-after

Here a quick before and after. The HDD upsite down was before 026d162 and is already fixed.

**Comment by websupporter** [comment]
Well, well. I just see, the other two icons need to be upsite down as well. I will fix this, but let's see first, if my approach is one, we could follow.

**Comment by Zodiac1978** [comment]
Looks like the paddings have to be adjusted a bit.

**Comment by websupporter** [comment]
Thanks @Zodiac1978. Sorry for my design blindness: Where? :thinking:

**Comment by timse201** [comment]
Memory should be more to the left
The hard drive 1px more to the left
Is the database smaller?

**Pull request merged**
