### PR TITLE
Prepare plugin for automatic deployments and add updated screenshots

### LINKED ISSUE #57: More Screenshots on WordPress.org
at the moment there is only 1 picture on WordPress.org
https://ps.w.org/cachify/assets/screenshot-1.png?rev=976963

There sould be more screenshots
like:
https://github.com/pluginkollektiv/assets/raw/master/cachify/images/cachify-toolbar-icon.png
https://www.pc-tweak.de/entwicklung/publish-remove.png
https://www.pc-tweak.de/entwicklung/settings.png

[#1 assets](https://github.com/pluginkollektiv/assets/pull/1)

### PR DESCRIPTION
**Pull request by 2ndkauboy**
Closes #57.

### CODE REVIEW

**Comment by Zodiac1978** [comment]
I can not give feedback about the workflow, but the last, fourth screenshot is just for the classic editor. In Gutenberg this does not work anymore. See: https://github.com/pluginkollektiv/cachify/issues/161#issuecomment-519147160

I think this should be mentioned in the caption. Maybe add "(classic editor)" or similar. What do you think?

**Comment by stklcode** [comment]
I'm currently working on a replacement for this feature as global options in plugin settings as suggested in the issue. So the settings screenshot is potentially outdated as well. But this should not block this PR. Screenshots naturally have to be updated from time to time.

For the current state of development, a comment like "(classic editor)" seems legit.

**Comment by 2ndkauboy** [comment]
I've added this screenshot, as the description was in the readme. I'll add the "(classic editor)" comment.

**Comment by krafit** [comment]
Thank you, @2ndkauboy. The deployment looks fine to me. I added the secrets to the repos settings.

**Pull request merged**
