### PR TITLE
minify CSS using Composer

### PR DESCRIPTION
**Pull request by stklcode**
* minify CSS using Composer instead of Grunt
* introduce Stylelint checks (CI to be done along with PHPCS/PHPUnit changes WIP)
* remove minified resources from SCM
  * add Composer build step to GH action for automatic deployment

### CODE REVIEW

**Review by bueltge — APPROVED** [review]
We should merge them because a great benefit to get the release a little bid easier.

**Comment by Zodiac1978** [comment]
This is out of my coding comfort zone, so I am not keen to merge this unless someone else takes the responsibility to do it.

If you approve a PR I will merge it (even if I don't know if this works and have not tested it). If you are fine with this workflow I can merge all those PRs (or I can give you the rights to do it yourself).

**Comment by bueltge** [comment]
@Zodiac1978 the workflow is fine for me. That's the point because I set an approved flag to this PR - BUT one person should manage a new release, including this PRs, because they're a more than one and a test is always important before release. An alternative we find a time frame, @stklcode, you, and I will also help, to merge this all and then preparation for release, testing. Communication about Slack.

**Comment by patrickrobrecht** [comment]
Changes included in #202.

**Pull request closed without merging**
