### PR TITLE
prepare release of v2.4.0 (#293)

### PR DESCRIPTION
**Pull request by stklcode**
* add changelog entries
* raise version number to 2.4.0
* raise "Tested up to:" to 6.6
* unify "since" comments

If you want to test the new plugin, you may use this package and install at own risk:

* ~[Release 2.4.0-beta.1](https://github.com/pluginkollektiv/cachify/releases/tag/2.4.0-beta.1) ([cachify.2.4.0-beta1.zip](https://github.com/pluginkollektiv/cachify/releases/download/2.4.0-beta.1/cachify.2.4.0-beta1.zip))~
* [Release 2.4.0-beta.2](https://github.com/pluginkollektiv/cachify/releases/tag/2.4.0-beta.2) ([cachify.2.4.0-beta2.zip](https://github.com/pluginkollektiv/cachify/releases/download/2.4.0-beta.2/cachify.2.4.0.beta2.zip))

### CODE REVIEW

**Comment by stklcode** [comment]
Briefly tested the release myself in a test container:
* both nginx 1.26.1 and Apache httpd  2.4.62
* PHP 8.3.10
* WP 6.6.1
* MySQL 8.4.2
* Valkey 7.2.6

Standard workflows look good, no obvious regressions. Not every edge case testet though.

**Comment by stklcode** [comment]
Updated after APC removal (#304, #305) and attached a new beta2.

**Comment by Zodiac1978** [comment]
The semicolons after the `Ifmodule` blocks are breaking everything, at least for me (every request fails with an error 500).

If I remove them, it works.

I have never seen them anywhere and cannot find them in the Apache docs as allowed.

**Comment by stklcode** [comment]
Good catch, apparently `s/&gt/>/g` left a stray semicolon :see_no_evil: Should be fixed by #309

**Pull request merged**
