### PR TITLE
prepare release of v2.3.2

### PR DESCRIPTION
**Pull request by stklcode**
should me merged **after** #226 

* declare plugin verison 2.3.2
* bump stable tag to 2.3.2
* add changelog and upgrade notice to README.txt

### CODE REVIEW

**Comment by Zodiac1978** [comment]
@stklcode Do you want to add the new "Tested up to: 5.8" here or do you want to open a new issue/PR for 5.8 testing?

**Comment by stklcode** [comment]
Already did this in beb65bb

We can of course split this, if you like, I do not have strong preference here.

**Comment by Zodiac1978** [comment]
I missed the commit. No need to split things up. Just overlooked it.

I am just waiting for some feedback on #226 and then we can merge and release 2.3.2.

**Review by pfefferle — APPROVED** [review]
LGTM

**Pull request merged**
